### ISSUE TITLE
'clickhouse_replica_id' is undefined

### ISSUE THREAD

**Issue by RouR** [nl2go/ansible-role-clickhouse#34]
Default variables, single, clean server (without zooker)

```
TASK [nl2go.clickhouse : Config | Set ClickHouse configuration file] **********************************************************************************************************************************************fatal: [devsrv]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'clickhouse_replica_id' is undefined"}
```

**Comment by andresmazzo** [comment]
@RouR did you find a workaround to the bug?

**Comment by RouR** [comment]
Yes, part of my playbook:
```
# ansible-galaxy install nl2go.clickhouse
# - downloading role from https://github.com/nl2go/ansible-role-clickhouse/archive/0.3.16.tar.gz
# - extracting nl2go.clickhouse to /home/alex/.ansible/roles/nl2go.clickhouse
# - nl2go.clickhouse (0.3.16) was installed successfully
---
- name: Install ClickHouse
  hosts: clickhouse_servers    
  become: yes

  roles:
  - custom_clickhouse # fixed error in nl2go.clickhouse  

  # https://github.com/nl2go/ansible-role-clickhouse/blob/master/defaults/main.yml
  vars:
    clickhouse_display_name: "{{inventory_hostname}}-node"
    clickhouse_replica_id: "-0" # display_name suffix
    # clickhouse_version: 20.5.2.7
    clickhouse_version: "*"
    clickhouse_users: # More settings: https://clickhouse.tech/docs/en/operations/settings/settings-users/
...
```
